sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - integration
    - 1.0.0-dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_TRAVISCI=phpcs WP_MULTISITE=0
    - php: 5.6
      env: WP_TRAVISCI=phpcs WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.4 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1
  fast_finish: true

install:
  - composer install

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      vendor/bin/phpunit --coverage-clover=coverage.xml
      WP_MULTISITE=1 vendor/bin/phpunit --coverage-clover=coverage.xml
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
